# completion cache path setup
typeset -g comppath="$HOME/.cache"
typeset -g compfile="$comppath/.zcompdump"

if [[ -d "$comppath" ]]; then
	[[ -w "$compfile" ]] || rm -rf "$compfile" >/dev/null 2>&1
else
	mkdir -p "$comppath"
fi

WORDCHARS=${WORDCHARS//\/} # Don't consider certain characters part of the word

# configure key keybindings
bindkey -e                                        # emacs key bindings
bindkey ' ' magic-space                           # do history expansion on space
bindkey '^[[1;5C' forward-word                    # ctrl + ->
bindkey '^[[1;5D' backward-word                   # ctrl + <-
bindkey '^X' edit-command-line                    # ctrl + x to open in editor

# Open command in editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^X' edit-command-line                    # ctrl + x

# Override -h and --help with bat
alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'

# History configurations
HISTFILE="$comppath/.zsh_history"
HISTSIZE=1000
SAVEHIST=2000
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt share_history         # share command history data

#######################################################
# GENERAL ALIAS'S
#######################################################

# Set the default editor
export EDITOR=nvim
export VISUAL=nvim
alias vi="nvim"
alias vim="nvim"

# Alias's to modified commands
alias ip="ip -c"
alias cp="cp -i"
alias mv="mv -i"
alias rm="trash -v"
alias mkdir="mkdir -p"
alias pst="wl-paste"
alias cpy="wl-copy"
alias urls="grep -oP -N --color=never 'http[s]?://\\S+'"

alias cd="z"
alias ..="cd .."
alias ls="eza --icons"
alias la="eza -a --icons"
alias ll="eza -l --icons --total-size"
alias lt="eza --icons --tree -I .git --group-directories-first"
alias open="xdg-open"

len() {
    echo ${#1}
}

export GOPAH="$HOME/.go"
export PATH="$PATH:$GOPATH/bin:$HOME/.local/bin:$HOME/.cargo/bin"
export MANPATH="/usr/share/man:/usr/local/share/man:$MANPATH"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
export _ZO_EXCLUDE_DIRS="/nix:/tmp:/proc:/sys:/dev"
export BAT_THEME="TwoDark"

if ! [ $NVIM ]; then
	clear; fastfetch -c examples/9.jsonc
	if ! [ $TMUX ]; then
		  $HOME/.local/bin/tmux-sessionizer.sh
	fi
fi

source <(fzf --zsh)
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh 
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
